# Generated by Django 4.0.4 on 2022-04-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='days',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
