# Generated by Django 4.0.4 on 2022-05-03 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_period_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='الاسم يجب ان يتكون من احرف و ارقام', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
